### ISSUE TITLE
action fails on non-standard semver tags

### ISSUE THREAD

**Issue by jhamman** [jacobtomlinson/gha-anaconda-package-version#6]
When using this action to get the latest JupyterLab tag, we've run into the following error:

```
 Get latest jupyterlab version1s
	/app/main.go:58 +0x8f4
Run jacobtomlinson/gha-anaconda-package-version@0.1.1
  with:
    org: conda-forge
    package: jupyterlab
/usr/bin/docker run --name d00b3300b7b2ec9b9040038f94ded32d4d7f75_0bc222 --label d00b33 --workdir /github/workspace --rm -e INPUT_ORG -e INPUT_PACKAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/pangeo-notebook-feedstock/pangeo-notebook-feedstock":"/github/workspace" d00b33:00b7b2ec9b9040038f94ded32d4d7f75
panic: strconv.ParseInt: parsing "0rc0": invalid syntax

goroutine 1 [running]:
github.com/coreos/go-semver/semver.Must(...)
	/go/src/github.com/coreos/go-semver/semver/semver.go:65
github.com/coreos/go-semver/semver.New(0xc0002eee28, 0x8, 0xc0002eee28)
	/go/src/github.com/coreos/go-semver/semver/semver.go:49 +0x6f
main.main()
	/app/main.go:58 +0x8f4
```

Best I can tell, the action is choking on this tag: `jupyterlab-2.1.0rc0`. I wonder if this action can/should filter out invalid tags before passing to SemVer.

cc @scotthq

xref: https://github.com/pangeo-bot/pangeo-notebook-feedstock/runs/569297990?check_suite_focus=true

**Comment by jacobtomlinson** [comment]
Yeah `jupyterlab-2.1.0rc0` isn't a valid semver tag, so I would expect this to be raised.

I think we should just catch the exception and ignore that version in the sorted list. If a tag isn't valid semver there isn't really a good way for us to sort it.

**Comment by jhamman** [comment]
+1 on this solution. Thanks @jacobtomlinson!
